---
- name: Create S3 bucket with versioning enabled
  hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - amazon.aws

  vars:
    bucket_name: anjali-demo-bucket  # bucket name must be unique globally
    region: us-west-2

  tasks:
    - name: Create S3 bucket
      amazon.aws.s3_bucket:
        name: "{{ bucket_name }}"
        state: present
        region: "{{ region }}"
      register: s3_result

    - name: Enable versioning on the bucket
      amazon.aws.s3_bucket:
        name: "{{ bucket_name }}"
        versioning: yes
        region: "{{ region }}"
        state: present

    - name: Show bucket
      debug:
        msg: "S3 bucket"
